PRODUTOS
ID,
CODIGO_PRODUTO,
DESCRICAO_PRODUTO,
ID_FORNECEDOR,
ID_VENDEDOR

CREATE TABLE PRODUTOS (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CODIGO_PRODUTO INT,
    DESCRICAO_PRODUTO VARCHAR(100),
    ID_FORNECEDOR INT,
    ID_VENDEDOR INT,
    FOREIGN KEY (ID_FORNECEDOR) REFERENCES FORNECEDORES(ID_FORNECEDOR),
    FOREIGN KEY (ID_VENDEDOR) REFERENCES VENDEDORES(ID_VENDEDOR)
);

INSERT INTO PRODUTOS VALUES
(NUll,1, 'Pão Francês', 101, 201),
(NUll,2, 'Croissant', 102, 202),
(NUll,3, 'Bolo de Chocolate', 103, 203),
(NUll,4, 'Pão de Queijo', 104, 204);

UPDATE PRODUTOS
SET ID_VENDEDOR = 202
WHERE CODIGO_PRODUTO = 1;

DELETE 
FROM PRODUTOS
WHERE CODIGO_PRODUTO = 1;


GRANT SELECT ON EMPRESA_DB.VENDAS TO 'ANA.ANALISTA'@'%';

GRANT INSERT ON EMPRESA_DB.VENDAS TO 'BRUNO.ESTAGIARIO'@'%';

GRANT SELECT, INSERT, UPDATE, DELETE ON EMPRESA_DB.VENDAS TO 'carla.gerente'@'%';

GRANT ALL PRIVILEGES ON EMPRESA_DB.VENDAS TO 'carla.gerente'@'%';

