USE _ABD_03361_A_FELIPE_LIMA_BIBLIOTECA;


-- CRIAR UM CONTROLE DE BIBLIOTECA
CREATE DATABASE _ABD_03361_A_FELIPE_LIMA_BIBLIOTECA;
-- TEREMOS OS DADOS DOS ALUNOS, SÉRIES DOS ALUNOS E DOS LIVROS, GENEROS E EMPRESTIMOS
 
-- 1 A TABELA GENEROS TEM OS CAMPOS ID E NOME_GENERO, POPULE EM SEGUIDA COM 5 GENEROS

 CREATE TABLE GENEROS(
	ID_GENERO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_GENERO VARCHAR(50) NOT NULL
);

INSERT INTO GENEROS (NOME_GENERO)
VALUES 
('Infantil'),
('Romance'),
('Suspense'),
('Ciência'),
('História');
 
-- 2 A TABELA LIVROS TEM OS CAMPOS ID, NOME_LIVRO, AUTOR, ID_GENERO, QTD_DISPONIVEL, PRECO, DATA_INSERCAO,
-- POPULE EM SEGUIDA EM COM 5 LIVROS QUE VOCÊ RECOMENDA SENDO ESSENCIAIS PARA QUALQUER UM
-- DICA: PARA DATA_INSERCAO USE O TIPO TIMESTAMP DEFAULT CURRENT_TIMESTAMP

CREATE TABLE LIVROS(
	ID_LIVRO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_LIVRO VARCHAR(100) NOT NULL,
    AUTOR VARCHAR(80) NOT NULL,
    ID_GENERO INT,
    QTD_DISPONIVEL INT,
    PRECO DECIMAL(8,2) NOT NULL,
    DATA_INSERCAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_GENERO) REFERENCES GENEROS(ID_GENERO)
);

INSERT INTO LIVROS (NOME_LIVRO, AUTOR, ID_GENERO, QTD_DISPONIVEL, PRECO)
VALUES
('1984', 'George Orwell', 1, 7, 49.90),               
('Dom Quixote', 'Miguel de Cervantes', 1, 5, 59.90),  
('Orgulho e Preconceito', 'Jane Austen', 2, 6, 39.90),
('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 4, 8, 29.90),
('Sapiens', 'Yuval Noah Harari', 5, 4, 69.90);

-- 3 CRIAR UMA TABELA DAS SÉRIES DOS ALUNOS COM O NOME DE SERIES COM OS CAMPOS ID, NOME_SERIE
-- POPULE EM SEGUIDA EXEMPLO: ('6º'), ('7º')

CREATE TABLE SERIES(
ID_SERIES INT AUTO_INCREMENT PRIMARY KEY,
NOME_SERIE VARCHAR(20) NOT NULL
);

INSERT INTO SERIES (NOME_SERIE)
VALUES ('6º'),
('7º'),
('8º'),
('9º');
 
-- 4 CRIAR A TABELA DE ALUNOS COM OS CAMPOS ID, NOME, ID_SERIE, NASCIMENTO
-- POPULE COM 10 ALUNOS

CREATE TABLE ALUNOS(
	ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	ID_SERIE VARCHAR(100) NOT NULL,
	NASCIMENTO DATE NOT NULL,
    FOREIGN KEY (ID_SERIE) REFERENCES SERIES(ID_ALUNO)
);
 
INSERT INTO ALUNOS (NOME, ID_SERIE, NASCIMENTO)
VALUES
('Lucas Pereira', 1, '2013-05-12'),
('Mariana Silva', 1, '2013-08-22'),
('Gabriel Santos', 2, '2012-11-03'),
('Ana Beatriz Costa', 2, '2012-03-15'),
('Rafael Almeida', 3, '2011-07-30'),
('Beatriz Oliveira', 3, '2011-09-18'),
('Felipe Rocha', 4, '2010-01-25'),
('Camila Fernandes', 4, '2010-12-10'),
('Thiago Souza', 4, '2010-06-02'),
('Juliana Martins', 3, '2011-04-07');
 
-- 5 TABELA EMPRESTIMOS 
-- ID, ID_ALUNO, ID_LIVRO, DATA_EMPRESTO TIMESTAMP DEFAULT CURRENT_TIMESTAMP, DEVOLVIDO BOOLEAN DEFAULT FALSE


CREATE TABLE EMPRESTIMOS(
	ID_EMPRESTIMO INT AUTO_INCREMENT PRIMARY KEY,
    ID_ALUNO INT,
    ID_LIVRO INT,
    DATA_EMPRESTIMO DATE,
    DEVOLVIDO BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO),
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVROS(ID_LIVRO)
);

-- 6 INSERIR NA TABELA DE EMPRESTIMOS A COLUNA DATA_DEVOLUCAO_PREVISTA
ALTER TABLE EMPRESTIMOS ADD DATA_DEVOLUCAO_PREVISTA DATE;
 
-- 7 POPULAR A TABELA EMPRESTIMOS COM 5 ITENS
SELECT * FROM EMPRESTIMOS;
INSERT INTO EMPRESTIMOS (ID_ALUNO,ID_LIVRO,DATA_EMPRESTIMO,DEVOLVIDO, DATA_DEVOLUCAO_PREVISTA) 
VALUES (1, 1, '2025-10-01', 0, '2025-10-15'),
(2, 2, '2025-10-03', 1, '2025-10-17'),
(3, 3, '2025-10-05', 0, '2025-10-19'),
(4, 4, '2025-10-07', 1, '2025-10-21'),
(5, 5, '2025-10-08', 0, '2025-10-22');

-- 8 MOSTRAR TODOS OS LIVDATA_EMPRESTO ROS DISPONÍVEIS COM QUANTIDADE MAIOR QUE 3
SELECT *
FROM EMPRESTIMOS 
WHERE DATA_EMPRESTIMO > 3;
                   
-- 9 MOSTRAR TODOS OS ALUNOS DA 6º SÉRIE
SELECT *
FROM ALUNOS
WHERE ID_SERIE = 1;
 
-- 10 REGISTRAR UM EMPRÉSTIMO (ALUNO PEDRO LIMA PEGOU "O HOBBIT" EM 2025-10-10 E PRETENDE DEVOLVER 2025-10-25
INSERT INTO EMPRESTIMOS (ID_ALUNO, ID_LIVRO, DATA_EMPRESTIMO, DEVOLVIDO, DATA_DEVOLUCAO_PREVISTA)
VALUES (7, 2, '2025-10-10', 0, '2025-10-25');
 
-- 11 DIMINUIR A QUANTIDADE DISPONÍVEL DO LIVRO "O HOBBIT" EM 1
-- DICA: PODE USAR SUBTRAÇÃO! QTD_DISPONIVEL = QTD_DISPONIVEL - 1
UPDATE LIVROS
SET QTD_DISPONIVEL = QTD_DISPONIVEL - 1
WHERE ID_LIVRO = 2;
 
-- 12 MOSTRAR O TOTAL DE LIVROS DISPONÍVEIS EM UMA COLUNA CHAMADA TOTAL_LIVROS
SELECT SUM(QTD_DISPONIVEL) AS TOTAL_LIVROS
FROM LIVROS;
 
-- 13 ALTERAR O NOME DA TABELA LIVROS PARA LIVROS_EM_ESTOQUE
RENAME TABLE LIVROS TO LIVROS_EM_ESTOQUE;
 
-- 14 MOSTRAR O VALOR TOTAL INVESTIDO EM LIVROS EM UMA COLUNA CHAMADA VALOR_TOTAL_BIBLIOTECA
-- DICA: USE SUM(COLUNA_1 * COLUNA_2)

SELECT SUM(PRECO * QTD_DISPONIVEL) AS VALOR_TOTAL_BIBLIOTECA
FROM LIVROS_EM_ESTOQUE;
 
-- 15 MOSTRAR OS LIVROS DISPONIVEIS COM
-- QUANTIDADE MAIOR QUE 2, PREÇO MAIOR QUE 50 REAIS E GÊNERO SEJA FANTASIA OU LITERATURA
-- DICA: USE WHERE E IN()
SELECT *
FROM LIVROS_EM_ESTOQUE
WHERE QTD_DISPONIVEL > 2 
AND PRECO > 50 
AND GENERO IN(4,5);

SELECT * FROM LIVROS_EM_ESTOQUE;

