CREATE DATABASE ABD_03361_A_FELIPE_LIMA;

USE ABD_03361_A_FELIPE_LIMA;

CREATE TABLE FAMILIA(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    PARENTESCO VARCHAR(50) NOT NULL,
    IDADE INT,
    CIDADE VARCHAR(50)
);

INSERT INTO FAMILIA(NOME, PARENTESCO, IDADE, CIDADE)
VALUES('SERGIO', 'PAI', 61, 'RIO DE JANEIRO');
INSERT INTO FAMILIA(NOME, PARENTESCO, IDADE, CIDADE)
VALUES('VALERIA', 'MÃE', 61, 'RIO DE JANEIRO');
INSERT INTO FAMILIA(NOME, PARENTESCO, IDADE, CIDADE)
VALUES('ALINE', 'IRMÃ', 39, 'RIO DE JANEIRO');
INSERT INTO FAMILIA(NOME, PARENTESCO, IDADE, CIDADE)
VALUES('JESSICA', 'ESPOSA', 32, 'SÃO PAULO');
INSERT INTO FAMILIA(NOME, PARENTESCO, IDADE, CIDADE)
VALUES('SOFIA', 'FILHA', 1, 'SÃO PAULO');

SELECT * FROM FAMILIA;

/* DROP DATABASE ADB_03361_FELIPE_LIMA;*/