USE ABD_03361_A_FELIPE_LIMA;

-- EU PRECISO CONTROLAR OS USUÁRIO, EU PRECISO TER UM USUÁRIO MASTER(ROOT), QUE POSSA
-- ADICIONAR OUTROS USUÁRIOS.
-- O USUÁRIO MASTER DEVE CONSEGUIR CRIAR NOVOS ITENS NA TABELA DE TRANSACOES(PAGAMENTOS
-- PARA PROFESSORES)

-- JÁ O USUÁRIO 'NORMAL' DEVE CONSEGUIR SOMENTE VISUALIZAR
-- TODOS OS USUÁRIOS DEVEM PERTENCER A GRUPOS, NINGUÉM FICA SEM GRUPO.
-- UM USUÁRIO PODE PERTENCER A MAIS DE UM GRUPO OU SOMENTE 1 (EXEMPLO DE GRUPO: FINANCIAL,
-- LEGAL, COMPLIANCE)
-- NINGUÉM PODE SER CADASTRADO DUAS VEZES.

-- MODELANDO NO BR MODELO EM DER
-- CRIAS AS TABELAS, SUAS RELAÇÕES E POPULÁ-LAS

-- 1 CRIAR UMA QUERY PARA RETORNAR SOMENTE O NOME DOS USUARIOS UTILIZANDO O 'AS' CHAMANDO ELES
-- DE NOMES_FUNCIONARIOS

-- 2 MOSTRAR TODOS OS GRUPOS EXISTENTES ORDENADOS PELO NOME DE FORMA ALFABÉTICA
-- DICA: USE ORDER BY NOME ASC

-- 3 MOSTRAR OS 3 USUARIOS MAIS NOVOS

-- 4 MOSTRAR OS USUARIOS DO TIPO MASTER

-- 5 MOSTRAR OS USUARIOS QUE PERTENCEM AO GRUPO FINANCIAL

-- 6 MOSTRAR AS TRANSAÇÕES FEITAS PELO TIPO MASTER

-- 7 MOSTRAR O TOTAL PAGO EM UMA COLUNA PROVISÓRIA CHAMADA VALOR_TOTAL_PAGO
-- DICA: USE O SUM() PARA SOMAR O VALOR E AS PARA ESCREVER O NOME DA COLUNA.


CREATE TABLE USUARIOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    TIPO_USUARIO VARCHAR(50) NOT NULL,
    CARGO VARCHAR(60) NOT NULL
);

CREATE TABLE TRANSACOES(
	ID_TRANSACAO INT AUTO_INCREMENT PRIMARY KEY,
    ID_USUARIO INT,
    NOME_PROFESSOR VARCHAR(100) NOT NULL,
    TIPO_TRANSACAO VARCHAR(50) NOT NULL,
    VALOR_PAGO DECIMAL(8,2),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

CREATE TABLE GRUPOS(
	ID_GRUPO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_GRUPO VARCHAR(100) NOT NULL
);