USE ABD_03361_A_FELIPE_LIMA;

-- 1 CRIE UMA TABELA CHAMADA COMIDAS_FAVORITAS COM OS CAMPOS: ID, NOME_PESSOA, COMIDA, TIPO
-- NOTA, CIDADE;

CREATE TABLE COMIDAS_FAVORITAS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_PESSOA VARCHAR(80) NOT NULL,
    COMIDA VARCHAR(60) NOT NULL,
    TIPO VARCHAR(30) NOT NULL,
    NOTA INT NOT NULL,
    CIDADE VARCHAR(50) NOT NULL
);

-- 2 INSIRA 5 REGISTROS NA TABELA COMIDAS_FAVORITAS
INSERT INTO COMIDAS_FAVORITAS (NOME_PESSOA, COMIDA,TIPO,NOTA,CIDADE) 
VALUES ('LUCAS','FEIJOADA', 'SALGADO', 8, 'RIO DE JANEIRO');
INSERT INTO COMIDAS_FAVORITAS (NOME_PESSOA, COMIDA,TIPO,NOTA,CIDADE) 
VALUES ('SOFIA','PAVÊ', 'DOCE', 9, 'SÃO PAULO');
INSERT INTO COMIDAS_FAVORITAS (NOME_PESSOA, COMIDA,TIPO,NOTA,CIDADE) 
VALUES ('GABRIEL','BIFE À CAVALO', 'SALGADO', 4, 'RIO DE JANEIRO');
INSERT INTO COMIDAS_FAVORITAS (NOME_PESSOA, COMIDA,TIPO,NOTA,CIDADE) 
VALUES ('LAURA','SORVETE', 'DOCE', 7, 'RIO DE JANEIRO');
INSERT INTO COMIDAS_FAVORITAS (NOME_PESSOA, COMIDA,TIPO,NOTA,CIDADE) 
VALUES ('PEDRO','HAMBURGUER', 'SALGADO', 10, 'SÃO PAULO');
INSERT INTO COMIDAS_FAVORITAS (NOME_PESSOA, COMIDA,TIPO,NOTA,CIDADE) 
VALUES ('JESSICA','MACARRÃO À BOLONHESA', 'SALGADO', 10, 'RECIFE');

-- 3 SELECIONE TODAS AS COMIDAS COM NOTA MAIOR QUE 8
SELECT * 
FROM COMIDAS_FAVORITAS
WHERE NOTA > 8;

-- 4 MOSTRE APENAS O NOME DAS PESSOAS E SUAS COMIDAS FAVORITAS DO TIPO DOCE ORDENADA 
-- PELO NOME
SELECT *
FROM COMIDAS_FAVORITAS
WHERE TIPO = 'DOCE'
ORDER BY NOME_PESSOA ASC;

-- 5 MOSTRE AS COMIDAS FAVORITAS DE QUEM MORA EM SÃO PAULO OU RIO DE JANEIRO: USE O IN
SELECT NOME_PESSOA, COMIDA, CIDADE
FROM COMIDAS_FAVORITAS
WHERE CIDADE IN ('SÃO PAULO','RIO DE JANEIRO');

-- 6 ATUALIZE A NOTA DE UMA COMIDA ESPECÍFICA PARA 10 DICA: UPDATE
SELECT * FROM COMIDAS_FAVORITAS;

UPDATE COMIDAS_FAVORITAS
SET NOTA = 6
WHERE ID = 5;

-- 7 ATUALIZE O TIPO DE TODAS AS COMIDAS QUE CONTENHAM A PALAVRA PIZZA PARA SALGADO DICA: USE LIKE
SET SQL_SAFE_UPDATES = 0;
UPDATE COMIDAS_FAVORITAS
SET TIPO = 'SALGADO'
WHERE COMIDA LIKE '%PIZZA%';

-- 8 EXCLUA TODAS AS COMIDAS QUE TENHAM NOTA MENOR QUE 5:
DELETE FROM COMIDAS_FAVORITAS
WHERE NOTA < 5;

-- DESAFIO
-- 9 MOSTRE O NOME DA PESSOA E A COMIDA FAVORITA ONDE O NOME_TENHA MAIS DE 10 CARACTERES
-- E A NOTA ESTEJA ENTRE 7 E 10 DICA: USE LENGTH() E BETWEEN
SELECT NOME_PESSOA, COMIDA, NOTA
FROM COMIDAS_FAVORITAS
WHERE LENGTH(NOME_PESSOA) > 10 AND NOTA BETWEEN 7 AND 10;


