USE ABD_03361_A_FELIPE_LIMA;

-- SELECIONA A FAMILIA
SELECT * FROM FAMILIA;

-- 1 ESCREVA UM SCRIPT QUE RETORNE SOMENTE AS PESSOAS MAIORES DE 35 ANOS
SELECT * 
FROM FAMILIA
WHERE IDADE > 35;

-- 2 ESCREVA UM SCRIPT QUE RETORNE SOMENTE A CIDADE DE São Paulo, USE LIKE.
SELECT * 
FROM FAMILIA
WHERE CIDADE LIKE 'São Paulo';

-- 3 ESCREVA UM SCRIPT QUE RETORNE AS PESSOAS QUE TEM IDADE ENTRE 18 E 20 ANOS.
SELECT * 
FROM FAMILIA
WHERE IDADE BETWEEN 18 AND 20;

-- 4 ESCREVA UM SCRIPT QUE RETORNE SOMENTE O NOME DAS PESSOAS COM IDADE MAIOR OU IGUAL A 22 ANOS.
SELECT NOME
FROM FAMILIA
WHERE IDADE >= 22;

-- 5 SOMENTE O NOME E IDADE DAS PESSOAS MENORES QUE 18 ANOS ORDENADOS POR ORDEM ASCENDENTEMENTE;

SELECT NOME, IDADE
FROM FAMILIA
WHERE IDADE < 18
ORDER BY IDADE ASC;

-- 6 PESSOAS QUE MORAM EM SAO PAULO OU RIO DE JANEIRO;
SELECT * 
FROM FAMILIA
WHERE CIDADE IN('São Paulo','Rio de Janeiro')
ORDER BY NOME ASC;

-- 7 NOME E IDADE DE PESSOAS QUE O NOME SEJA MAIOR QUE 15 CARACTERES E QUE A CIDADE SEJA 
-- SÃO PAULO EM ORDEM ASC

SELECT NOME, IDADE
FROM FAMILIA
WHERE LENGTH(NOME) > 10 AND CIDADE = 'São Paulo'
ORDER BY IDADE ASC;
