-- 1 CRIAR A BASE DE DADOS
USE ABD_03361_A_FELIPE_LIMA;
 
-- 2 CRIAR A TABELA DE CLIENTES_BANCO_ITAU
-- CAMPOS:
-- ID_CLIENTE (INT AUTO_INCREMENT, PRIMARY KEY)
-- NOME_CLIENTE (VARCHAR 100)
-- CPF (VARCHAR 11)

CREATE TABLE CLIENTES_BANCO_ITAU(
	ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOME_CLIENTE VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL
);
 
-- 3 CRIAR A TABELA DE CONTAS
-- CAMPOS:
-- ID_CONTA (INT AUTO_INCREMENT, PRIMARY KEY)
-- ID_CLIENTE (INT, FK)
-- SALDO (DECIMAL 10,2)
-- TIPO_CONTA (VARCHAR 20)


CREATE TABLE CONTAS(
	ID_CONTA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT,
    SALDO DECIMAL(10,2),
    TIPO_CONTA VARCHAR(20),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES_BANCO_ITAU(ID_CLIENTE)
);
 
-- 4 POPULAR A TABELA CLIENTES COM 5 CLIENTES SEM DEFINIR AS COLUNAS

INSERT INTO CLIENTES_BANCO_ITAU
VALUES
(NULL,'João Silva', '12345678901'),
(NULL,'Maria Oliveira', '98765432100'),
(NULL,'Carlos Pereira', '23456789012'),
(NULL,'Fernanda Souza', '34567890123'),
(NULL,'Roberto Almeida', '45678901234');


SELECT * FROM CLIENTES_BANCO_ITAU;
 
-- 5 POPULAR A TABELA CONTAS COM 5 CONTAS
 INSERT INTO CONTAS VALUES (NULL,1, 1500.00, 'Corrente'),
(NULL,2, 3200.50, 'Poupança'),
(NULL,3, 450.75, 'Corrente'),
(NULL,4, 12300.00, 'Corrente'),
(NULL,5, 875.90, 'Poupança');

SELECT * FROM CONTAS;

-- 6 EXERCÍCIO DE TRANSACÇÃO COM RELAÇÃO ENTRE CLIENTES E CONTAS
-- SITUAÇÃO: QUEREMOS TRANSFERIR 600 REAIS DE JOÃO SILVA PARA PEDRO LIMA
-- PASSO 1: INICIAR A TRANSACAO (BEGIN)
-- PASSO 2: DIMINUIR SALDO DE JOÃO SILVA
-- PASSO 3: AUMENTAR SALDO DE PEDRO LIMA
-- PASSO 4: SE SALDO DE JOÃO FICAR NEGATIVO, FAZER ROLLBACK, SENÃO COMMIT

START TRANSACTION;

UPDATE CONTAS
SET SALDO = SALDO - 600
WHERE ID_CONTA = 1;

UPDATE CONTAS
SET SALDO = SALDO + 600
WHERE ID_CONTA = 4;

SELECT saldo FROM CONTAS WHERE ID_CONTA = 1;

