-- CONTEXTO: SISTEMA DE GESTÃO DE ESCRITÓRIO DE ADVOCACIA
 DROP DATABASE ABD_03361_A_FELIPE_LIMA_GESTAO_ADVOCACIA_2025;
-- NOME DA BASE DE DADOS: GESTAO_ADVOCACIA_2025
CREATE DATABASE ABD_03361_A_FELIPE_LIMA_GESTAO_ADVOCACIA_2025;
 
-- O OBJETIVO É RELACIONAR ADVOGADOS, CLIENTES, CASOS E AUDIENCIAS
-- E REALIZAR CONSULTAS USANDO DIFERENTES TIPOS DE JOIN
 
 
-- 1 USAR A BASE COM SEUS NOMES
 USE ABD_03361_A_FELIPE_LIMA_GESTAO_ADVOCACIA_2025;

-- 2 CRIAR A TABELA ADVOGADOS
-- CAMPOS: id, nome, oab, especialidade
CREATE TABLE ADVOGADOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	OAB VARCHAR(15)NOT NULL,
	ESPECIALIDADE VARCHAR(80) NOT NULL
);
 
-- 3 CRIAR A TABELA CLIENTES
-- CAMPOS: id, nome, cpf, cidade
CREATE TABLE CLIENTES(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	CIDADE VARCHAR(50) NOT NULL
);
 
-- 4 CRIAR A TABELA CASOS
-- CAMPOS: id, id_advogado, id_cliente, descricao, status, data_abertura
-- RELACIONAR id_advogado COM ADVOGADOS
-- RELACIONAR id_cliente COM CLIENTES
CREATE TABLE CASOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_ADVOGADO INT,
	ID_CLIENTE INT,
	DESCRICAO TEXT NOT NULL,
	STATUS VARCHAR(20),
	DATA_ABERTURA DATE,
	FOREIGN KEY (ID_ADVOGADO) REFERENCES ADVOGADOS(ID),
	FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);
 
-- 5 CRIAR A TABELA AUDIENCIAS
-- CAMPOS: id, id_caso, data_audiencia, local, resultado
-- RELACIONAR id_caso COM CASOS
CREATE TABLE AUDIENCIAS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
	ID_CASO INT,
	data_audiencia DATE NOT NULL,
	LOCAL VARCHAR(50) NOT NULL,
	RESULTADO VARCHAR(50) NOT NULL,
	FOREIGN KEY (ID_CASO) REFERENCES CASOS(ID)
);

 
-- 6 POPULAR TODAS AS TABELAS COM PELO MENOS 5 REGISTROS

INSERT INTO ADVOGADOS 
VALUES (NULL,'Ana Souza', 'OAB-SP 123456', 'Direito Civil'),
(NULL,'Carlos Silva', 'OAB-RJ 234567', 'Direito Penal'),
(NULL,'Fernanda Oliveira', 'OAB-MG 345678', 'Direito Trabalhista'),
(NULL,'José Pereira', 'OAB-PR 456789', 'Direito Tributário'),
(NULL,'Mariana Costa', 'OAB-BA 567890', 'Direito Empresarial'),
(NULL,'Rafael Martins', 'OAB-RS 678901', 'Direito Ambiental'),
(NULL,'Patrícia Lima', 'OAB-SP 789012', 'Direito Imobiliário'),
(NULL,'Lucas Almeida', 'OAB-PE 890123', 'Direito Internacional'),
(NULL,'Julia Santos', 'OAB-MT 901234', 'Direito de Família'),
(NULL,'Gustavo Costa', 'OAB-DF 012345', 'Direito Digital'),
(NULL,'Ricardo Pereira Lima', 'OAB-SP 987654', 'Direito Ambiental');

SELECT * FROM ADVOGADOS;

INSERT INTO CLIENTES VALUES
(NULL,'João Silva', '123.456.789-01', 'São Paulo'),
(NULL,'Maria Oliveira', '234.567.890-12', 'Rio de Janeiro'),
(NULL,'Carlos Almeida', '345.678.901-23', 'São Paulo'),
(NULL,'Fernanda Souza', '456.789.012-34', 'Porto Alegre'),
(NULL,'Rafael Costa', '567.890.123-45', 'Curitiba'),
(NULL,'Patrícia Lima', '678.901.234-56', 'São Paulo'),
(NULL,'Lucas Santos', '789.012.345-67', 'Fortaleza'),
(NULL,'Ana Pereira', '890.123.456-78', 'Rio de Janeiro'),
(NULL,'Juliana Martins', '901.234.567-89', 'Curitiba'),
(NULL,'Gustavo Rocha', '012.345.678-90', 'Porto Alegre'),
(NULL,'Pedro Henrique Oliveira', '987.654.321-00', 'São Paulo');

INSERT INTO CASOS VALUES
(NULL,1, 3, 'Ação de indenização por danos materiais e morais', 'Em andamento', '2023-07-15'),
(NULL,2, 5, 'Defesa em processo de tráfico de drogas', 'Concluído', '2023-08-02'),
(NULL,3, 8, 'Divórcio litigioso com disputa de guarda de filhos', 'Em andamento', '2023-09-01'),
(NULL,4, 2, 'Revisão de impostos e pagamento de tributos federais', 'Em andamento', '2023-06-21'),
(NULL,5, 10, 'Assessoria em abertura de empresa no setor de tecnologia', 'Concluído', '2023-05-13'),
(NULL,6, 6, 'Consulta sobre questão ambiental e licenciamento', 'Concluído', '2023-04-30'),
(NULL,7, 7, 'Ação de reparação de danos por acidente de trânsito', 'Em andamento', '2023-09-10'),
(NULL,8, 1, 'Consulta sobre regularização de documentos imigratórios', 'Concluído', '2023-03-22'),
(NULL,9, 4, 'Processo de guarda compartilhada e alimentos', 'Em andamento', '2023-08-18'),
(NULL,10, 9, 'Consultoria sobre proteção de dados e segurança digital', 'Em andamento', '2023-07-25');
INSERT INTO CASOS VALUES
(NULL,1, 8, 'Defesa em caso de acusação de fraude empresarial', 'Em andamento', '2025-07-01'),
(NULL,NULL, NULL, 'Defesa em caso de acusação de fraude empresarial', 'Em andamento', '2023-10-01'),
(NULL,NULL, NULL, 'Consultoria jurídica para registro de marca', 'Concluído', '2023-09-15');

INSERT INTO AUDIENCIAS VALUES
(NULL,1, '2023-08-10', 'Fórum Central - São Paulo', 'Audiência adiada'),
(NULL,2, '2023-08-15', 'Fórum de Belo Horizonte', 'Sentença favorável ao réu'),
(NULL,3, '2023-09-05', 'Fórum Regional - Rio de Janeiro', 'Acordo entre as partes'),
(NULL,4, '2023-06-25', 'Fórum de Curitiba', 'Sentença favorável ao autor'),
(NULL,5, '2023-07-17', 'Fórum de Salvador', 'Sentença favorável ao réu'),
(NULL,6, '2023-04-12', 'Fórum de Fortaleza', 'Audiência adiada'),
(NULL,7, '2023-09-18', 'Fórum de Porto Alegre', 'Ação arquivada'),
(NULL,8, '2023-03-25', 'Fórum de Recife', 'Acordo entre as partes'),
(NULL,9, '2023-08-22', 'Fórum de Manaus', 'Sentença favorável ao autor'),
(NULL,10, '2023-07-30', 'Fórum de Brasília', 'Audiência adiada');

  
-- CONSULTAS (EXERCÍCIOS):
 
-- 7 INNER JOIN
-- MOSTRAR O NOME DO CLIENTE, O NOME DO ADVOGADO E A DESCRIÇÃO DO CASO

SELECT CS.NOME AS NOME_CLIENTE, 
	   ADV.NOME AS NOME_ADVOGADO, 
	   CA.DESCRICAO
FROM CLIENTES CS
INNER JOIN CASOS CA 
ON CS.ID = CA.ID_CLIENTE
INNER JOIN ADVOGADOS ADV 
ON CA.ID_ADVOGADO = ADV.ID;
 
-- 8 LEFT JOIN
-- MOSTRAR TODOS OS CLIENTES, MESMO OS QUE AINDA NÃO TÊM NENHUM CASO

SELECT CS.NOME AS NOME_CLIENTE, CA.DESCRICAO
FROM CLIENTES CS
LEFT JOIN CASOS CA 
ON CS.ID = CA.ID_CLIENTE;

 
-- 9 RIGHT JOIN
-- MOSTRAR TODOS OS CASOS, MESMO OS QUE AINDA NÃO POSSUEM CLIENTE DEFINIDO

SELECT CS.NOME AS NOME_CLIENTE, CA.DESCRICAO
FROM CLIENTES CS
RIGHT JOIN CASOS CA 
ON CS.ID = CA.ID_CLIENTE;

 
-- 10 FULL JOIN (USAR UNION)
-- MOSTRAR TODOS OS CLIENTES E CASOS, MESMO SEM RELAÇÃO ENTRE ELES



SELECT CS.NOME AS NOME_CLIENTE, CA.DESCRICAO
FROM CLIENTES CS
LEFT JOIN CASOS CA 
ON CS.ID = CA.ID_CLIENTE

UNION ALL

SELECT CS.NOME AS NOME_CLIENTE, CA.DESCRICAO
FROM CLIENTES CS
RIGHT JOIN CASOS CA 
ON CS.ID = CA.ID_CLIENTE
WHERE CS.ID IS NULL;

SELECT CS.NOME AS NOME_CLIENTE, CA.DESCRICAO
FROM CLIENTES CS
LEFT JOIN CASOS CA ON CS.ID = CA.ID_CLIENTE

UNION ALL

SELECT CS.NOME AS NOME_CLIENTE, CA.DESCRICAO
FROM CLIENTES CS
RIGHT JOIN CASOS CA ON CS.ID = CA.ID_CLIENTE
WHERE CS.ID IS NULL;
 
-- 11 CROSS JOIN
-- GERAR UMA COMBINAÇÃO ENTRE TODOS OS ADVOGADOS E TODOS OS CLIENTES
-- (POSSÍVEIS RELAÇÕES DE ATENDIMENTO)

SELECT CS.NOME AS NOME_CLIENTE, 
	   ADV.NOME AS NOME_ADVOGADO
FROM CLIENTES CS  
CROSS JOIN ADVOGADOS ADV;     
 
-- 12 MOSTRAR OS CASOS QUE ESTÃO COM STATUS 'EM ANDAMENTO' E
-- QUE FORAM ABERTOS DEPOIS DE '2025-01-01'
-- USAR INNER JOIN E WHERE
SELECT ADV.NOME AS NOME_ADVOGADO,
	   CA.DESCRICAO,
       CA.STATUS_PROCESSO,
       CA.DATA_ABERTURA
FROM CASOS CA
INNER JOIN ADVOGADOS ADV
ON CA.ID_ADVOGADO = ADV.ID
WHERE STATUS_PROCESSO = 'Em andamento' AND DATA_ABERTURA > '2025-01-01';
 
-- 13 MOSTRAR CADA ADVOGADO E QUANTOS CASOS ELE POSSUI
-- USAR GROUP BY E COUNT
SELECT * FROM CASOS;

SELECT ADV.NOME, COUNT(CA.ID_ADVOGADO) AS QUANTIDADE_CASOS
FROM ADVOGADOS ADV
INNER JOIN CASOS CA 
ON ADV.ID = CA.ID_ADVOGADO
GROUP BY ADV.NOME, CA.ID_ADVOGADO;
 
-- 14 MOSTRAR OS CLIENTES ORDENADOS PELO NOME (A–Z)
-- E SUAS RESPECTIVAS CIDADES

SELECT NOME, CIDADE
FROM CLIENTES
ORDER BY NOME ASC;
 
-- 15 MOSTRAR O TOTAL DE AUDIENCIAS REALIZADAS EM UMA COLUNA CHAMADA TOTAL_AUDIENCIAS
-- USAR COUNT E AS

SELECT COUNT(ID_CASO) AS TOTAL_AUDIENCIAS
FROM AUDIENCIAS;
 
-- 16 MOSTRAR OS CLIENTES DA CIDADE DE 'SÃO PAULO' E OS CASOS ASSOCIADOS
-- USAR INNER JOIN E WHERE

SELECT CS.NOME AS NOME_CLIENTE,
	   CS.CIDADE,
	   CA.DESCRICAO AS DESCRICAO_CASO
FROM CLIENTES CS
INNER JOIN CASOS CA
ON CS.ID = CA.ID_CLIENTE
WHERE CS.CIDADE = 'SÃO PAULO';
 
-- 17 MOSTRAR OS ADVOGADOS QUE NÃO POSSUEM NENHUM CASO
-- USAR LEFT JOIN E IS NULL

SELECT * FROM CASOS;

SELECT * FROM ADVOGADOS;

SELECT ADV.NOME AS NOME_ADVOGADO, CA.DESCRICAO
FROM ADVOGADOS ADV
LEFT JOIN CASOS CA
ON ADV.ID = CA.ID_ADVOGADO
WHERE ID_ADVOGADO IS NULL;
 
-- 18 MOSTRAR O NÚMERO TOTAL DE CASOS EM CADA STATUS (EX: 'EM ANDAMENTO', 'ENCERRADO')
-- USAR GROUP BY, COUNT E AS

SELECT STATUS_PROCESSO, COUNT(STATUS_PROCESSO) AS NUM_CASOS
FROM CASOS
GROUP BY STATUS_PROCESSO;
 
-- 19 MOSTRAR O ADVOGADO COM MAIS CASOS CADASTRADOS
-- DICA: USAR GROUP BY, ORDER BY E LIMIT 1

SELECT ADV.NOME, COUNT(CA.ID_ADVOGADO) AS NUM_CASOS
FROM ADVOGADOS ADV
INNER JOIN CASOS CA
ON ADV.ID = CA.ID_ADVOGADO
GROUP BY ADV.NOME
ORDER BY NUM_CASOS DESC
LIMIT 1;

 